[mysql_eshows]
host = "eshows-1.czzecscahytf.us-east-2.rds.amazonaws.com"
port = 6303
database = "eshows"
username = "gabriel.cunha@eshows.com.br"
password = "N97750803559115"

[mysql_grupoe]
host = "homolog.cvuwkhnpr3rt.us-east-2.rds.amazonaws.com"
port = 6303
database = "EPM_GRUPOE"
username = "grupo_e_user"
password = "X47QWTEFzrezuPtcd"
